name: ravi
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  url_strategy: ^0.2.0
  http: ^1.1.2
  json_serializable: ^6.7.1
  flutter_markdown: ^0.6.18
  highlight_text: ^1.7.0
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_code_editor: ^0.3.1
  google_fonts: ^6.1.0
  flutter_highlight: ^0.7.0
  cloud_functions: ^4.5.8
  firebase_auth: ^4.15.3
  flutter_bloc: ^8.1.3
  firebase_core: ^2.20.0
  cloud_firestore: ^4.13.6
  markdown_widget:
   git:
    url: https://github.com/asjqkkkk/markdown_widget
    ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/png/
